version: '3.8'

services:
  mcp-mattermost:
    build: .
    container_name: mcp-mattermost
    environment:
      # Mattermost configuration (required)
      - MATTERMOST_URL=${MATTERMOST_URL}
      - MATTERMOST_TOKEN=${MATTERMOST_TOKEN}

      # Neo4j configuration (optional)
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}

      # Cursor integration (optional)
      - CURSOR_USER_ID=${CURSOR_USER_ID}
      - CURSOR_USER_NAME=${CURSOR_USER_NAME}
      - CURSOR_USER_EMAIL=${CURSOR_USER_EMAIL}
      - CURSOR_USER_TEAM=${CURSOR_USER_TEAM}

      # Node environment
      - NODE_ENV=production
    depends_on:
      - neo4j
    volumes:
      # Mount a volume if you need persistent data or configuration
      - ./data:/app/data
    networks:
      - mcp-network
    restart: unless-stopped

  neo4j:
    image: neo4j:5.17-community
    container_name: neo4j-mcp
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-password}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - mcp-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  mcp-network:
    driver: bridge
